config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  post "/search", to: "static_pages#search"
  get "/sign_up", to: "users#new"
  get "/log_in", to: "sessions#new"
  post "/sign_up", to: "users#create"
  post "/log_in", to: "sessions#create"
  delete "/log_out", to: "sessions#destroy"
  
  resources :users do
    resources :relationships, only: :index
  end
  resources :images do
    collection do
      match "search" => "images#search", via: [:get, :post], as: :search
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :comments, dependent: :destroy
  has_many :like_images, dependent: :destroy

  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :image, presence: true
  validates :address, presence: true
  validate  :picture_size

  scope :order_by_created_at, ->{order created_at: :desc}
  scope :search_address, -> key{where("address LIKE ? OR description LIKE ?", "%#{key}%", "%#{key}%") if key.present?}
  scope :images_feed, ->user{where user_id: user.following_ids << user.id}

  mount_uploader :image, ImageUploader

  private
  def picture_size
    if image.size > 5.megabytes
      errors.add :picture, I18n.t("warning-max-size")
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :logged_in_user, except: [:show, :index]
  before_action :correct_user, only: [:destroy, :edit, :update]

  def index
    if params[:q].blank?
      @images = current_user.feed.order_by_created_at.paginate page: params[:page]
    else
      @images = Image.search_address(params[:q][:address]).order_by_created_at
    end
  end

  def show
    @image = Image.find_by id: params[:id]
    unless @image
      flash[:error] = t "image-not-found"
      redirect_to root_url
    end
  end

  def new
    @image = Image.new
    @categories = Category.all
  end

  def create
    @image = Image.new image_params
    @image.user_id = current_user.id
    if @image.save
      flash[:success] = t "image.message.success_created_image"
      redirect_to @image
    else
      @categories = Category.all
      render :new
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    if @image.update_attributes image_params
      flash[:success] = t "image.message.success_updated_image"
      redirect_to @image
    else
      render :edit
    end
  end

  def destroy
    @image.destroy
    flash[:success] = t "image.message.success_deleted_image"
    redirect_to root_url
  end

  def search
    index
    render :index
  end

  private

  def image_params
    params.require(:image).permit :user_id, :image, :address, :category_id ,
      :description, :created_at, :image_cache
  end

  def correct_user
    @image = current_user.images.find_by id: params[:id]
    redirect_to root_url unless @image
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-image">
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.label :address, t("image.address") %>
    <%= f.text_field :address, class: "form-control" %>
    <%= f.label :image, t("image.image") %>
    <%= f.file_field :image, id: "image-file" %>
    <%= f.hidden_field :image_cache %>
    <%= f.label :category_id, t("image.category") %>
    <%= f.select :category_id, @categories.map{|category| 
      [category.name, category.id]}, {}, class: "form-control" %>

    <%= f.label :description, t("image.description") %>
    <%= f.text_area :description, class: "form-control" %>

    <%= f.submit yield(:button_text),
      class: "btn btn-primary btn-create btn-lg" %>
    <%= link_to t("action.cancel"), @image.address ? @image : root_path,
      class: "btn btn-danger btn-cancel btn-lg" %>
  </div>
<% end %>

app/views/images/_image.html.erb
<li id="image-<%= image.id %>">
  <%= link_to gravatar_for(image.user, size: 50), image.user %>
  <span class="user"><%= link_to image.user.name, image.user %></span>
  <span class="address">
    <%= t "image.address" %> : <%= image.address %>
  </span>
  <span class="category"><%= t "image.category" %> : 
    <%= image.category.name %></span>
  <span class="more"><%= t "image.description" %> : 
    <%= image.description %></span>
  <span class="address">
    <%= link_to image_tag(image.image.large_size.url), image %>
  </span>
  <span class="timestamp">
    <%= t "posted" %>
    <%= time_ago_in_words image.created_at %>
    <%= t "ago" %>
    <% if image.user.current_user? current_user %>
      <%= link_to t("action.edit"), edit_image_path(image) %> | 
      <%= link_to t("action.delete"), image, method: :delete,
        data: {confirm: t("you_sure")} %>
    <% end %>
  </span>
</li>

app/views/images/edit.html.erb
<% provide :title, t("user.update-image") %>
<%= provide :button_text, t("action.update") %>
<h1><%= t "user.update-image" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/images/index.html.erb
<% provide :title, t("action.search") %>
<% if @images.any? %>
  <ol class="images">
    <%= render @images %>
  </ol>
<% end %>

app/views/images/new.html.erb
<% provide :title, t("user.upload-image") %>
<%= provide :button_text, t("action.upload") %>
<h1><%= t "user.upload-image" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/images/show.html.erb
<% provide :title, t("action.show") %>
<div class="images">
  <%= link_to gravatar_for(@image.user, size: 50), @image.user %>
  <span class="user"><%= link_to @image.user.name, @image.user %></span>
  <span class="address">
    <%= t "image.address" %> : <%= @image.address %>
  </span>
  <span class="category"><%= t "image.category" %> : 
    <%= @image.category.name %></span>
  <span class="more"><%= t "image.description" %> : 
    <%= @image.description %></span>
  <span class="address">
    <%= image_tag @image.image.larger_size.url %>
  </span>
  <span class="timestamp">
    <%= t "posted" %>
    <%= time_ago_in_words @image.created_at %>
    <%= t "ago" %>
    <% if @image.user.current_user? current_user %>
      <%= link_to t("action.edit"), edit_image_path(@image) %> | 
      <%= link_to t("action.delete"), @image, method: :delete,
        data: {confirm: t("you_sure")} %>
    <% end %>
  </span>
</div>