config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  post "/search", to: "static_pages#search"
  get "/sign_up", to: "users#new"
  get "/log_in", to: "sessions#new"
  post "/sign_up", to: "users#create"
  post "/log_in", to: "sessions#create"
  delete "/log_out", to: "sessions#destroy"
  
  resources :users do
    resources :relationships, only: :index
  end
  resources :images do
    collection do
      match "search" => "images#search", via: [:get, :post], as: :search
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row">
    <div class="col-md-4">
      <span class="copyright"><%= t :copyright %> &copy; <%= t :team %></span>
    </div>
    <div class="col-md-4">
      <ul class="list-inline social-buttons">
        <li><a href="#"><i class="fa fa-twitter"></i></a>
        </li>
        <li><a href="#"><i class="fa fa-facebook"></i></a>
        </li>
        <li><a href="#"><i class="fa fa-linkedin"></i></a>
        </li>
      </ul>
    </div>
    <div class="col-md-4">
      <ul class="list-inline quicklinks">
        <li><%= link_to t(:privacy_policy), "#" %>
        </li>
        <li><%= link_to t(:terms), "#" %>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("title"), root_path, id: "logo" %>
    <%= search_form_for @q, url: search_images_path, html: { method: :post }  do |f| %>
    <div class="text-search col-md-4 ui search">
      <%= f.text_field :address, id: "search", placeholder: t("action.search") %>
    </div>
    <div class="search-button col-md-1">
      <%= f.submit "", class: "btn" %>
    </div>
    <% end %>
    <div class="results"></div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), root_path %></li>
        <li><%= link_to t("about"), about_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("user.users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle",
              data: {toggle: "dropdown"} do %>
              <% if current_user.name.length > 12 %>
                <%= truncate current_user.name, length: 12 %>
              <% else %>
                <%= current_user.name %>
              <% end %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("user.profile"), current_user %></li>
              <li><%= link_to t("user.setting"), edit_user_path(current_user) %></li>
              <li><%= link_to t("user.new-image"), new_image_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("login.log-out"), log_out_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("login.log-in"), log_in_path %></li>
          <li><%= link_to t("signup.sign-up"), sign_up_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application",
  "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      
    </div>
    <div class="container">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>